name: Daily Job

on:
  schedule:
    - cron: '20 40 * * *' 

jobs:
  run_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run Python Script
        run: python geturl.py
