name: Daily Job

on:
  schedule:
    - cron: '13 43 * * *'  # 매일 22:20에 실행

jobs:
  run_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        run: python Software_proj/geturl.py
